version: '3.1'

services:

  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: usersdb

  adminer:
    image: adminer
    container_name: mysql_client
    restart: always
    ports:
      - 8080:8080
    links:
      - mysqldb